#screen
SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080

#player
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3

#asteroid
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

#scoreboard
FONT_SIZE = 28
FONT_COLOR = (65, 255, 0)
SCORE_POSITION = (10, 10)

#power-ups
POWERUP_RADIUS = 15
POWERUP_SPAWN_RATE = 12.5  # seconds

